environment:
  global:
    PROJECT_NAME: uploads-im-client-rs
    # TODO: Clippy version
  matrix:
    # Stable channel
    - TARGET: i686-pc-windows-gnu
      CHANNEL: stable
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
    # Beta channel
    - TARGET: i686-pc-windows-gnu
      CHANNEL: beta
    - TARGET: i686-pc-windows-msvc
      CHANNEL: beta
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: beta
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: beta
      # Nightly channel
    - TARGET: i686-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: i686-pc-windows-msvc
      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly
    # Rustfmt
    - NAME: Rustfmt
      TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
    # Clippy
    - NAME: Clippy
      TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable

matrix:
  allow_failures:
    - CHANNEL: nightly

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build: false
shallow_clone: true

test_script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose

for:
  - matrix:
      only:
        - NAME: Rustfmt
    before_test:
      - rustup component add rustfmt
    test_script:
      - cargo fmt -- --check

  - matrix:
      only:
        - NAME: Clippy
    before_test:
      - rustup component add clippy
    test_script:
      - cargo clippy -- -D clippy

cache:
  - target
  - C:\Users\appveyor\.cargo\registry
