environment:
  global:
    PROJECT_NAME: uploads-im-client-rs
  matrix:
    # Stable channel
    - TARGET: i686-pc-windows-gnu
      CHANNEL: stable
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
    # Beta channel
    - TARGET: i686-pc-windows-gnu
      CHANNEL: beta
    - TARGET: i686-pc-windows-msvc
      CHANNEL: beta
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: beta
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: beta
    # Nightly channel
    - TARGET: i686-pc-windows-gnu
      CHANNEL: nightly-2018-06-16
    - TARGET: i686-pc-windows-msvc
      CHANNEL: nightly-2018-06-16
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: nightly-2018-06-16
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly-2018-06-16

matrix:
  allow_failures:
    - CHANNEL: nightly-2018-06-16

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build: false
shallow_clone: true

before_build:
  - rustup install nightly-2018-06-18
  - cargo +nightly install clippy --version=0.0.208 --force
  - cargo +nightly install rustfmt-nightly --force

test_script:
  - cargo test
  - cargo +nightly clippy
  - cargo +nightly fmt -- --write-mode diff

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

cache:
  - target
  - C:\Users\appveyor\.cargo\registry
