language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - rustup install nightly
  - cargo +nightly install clippy

script:
  - cargo test
  - cargo +nightly clippy

git:
  depth: 1

notifications:
  email:
    on_success: never
